I need to fix navigation.
java.lang.IllegalStateException: View android.widget.FrameLayout{7b4f76c V.E...... ........ 0,0-1080,1895} does not have a NavController set